### ISSUE TITLE
Is there any description for the printing of row info?

### ISSUE THREAD

**Issue by Cancer29** [ZXGuesser/teletext-decoder#3]
Row 1: ⟦01⟧⟦1D⟧⟦03⟧      FOTBALL - ELITESERIEN 
Row 18: ⟦01⟧16.Aalesund     12   1  3  8  16-38   6

what is the meaning of the digits in brackets （“[]”）？

**Comment by ZXGuesser** [comment]
That's the control codes, as printing the raw characters upsets some text editors.
